import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createResetMonitorController, resetIntervalHours } from '../lib/reset-monitor.mjs';
import { acquireMonitorLock, readResetMonitorStatus, resetIntervalMinutes } from '../lib/reset-monitor-store.mjs';
import { tickResetMonitor } from '../lib/reset-monitor-worker.mjs';
import { readResetAnnouncements } from '../lib/reset-announcements.mjs';
import { classifyResetPost, extractResetTime } from '../lib/reset-classifier.mjs';
import { createResetMonitorServicePlan, installResetMonitorService } from '../lib/reset-monitor-service.mjs';

const NOW = Date.parse('2026-09-27T12:00:00Z');
const POST = { sourceUrl: 'https://x.com/thsottiaux/status/2100000000000000001', publishedAt: new Date(NOW).toISOString() };
async function fixture(t) {
  const root = await mkdtemp(path.join(tmpdir(), 'aiyou-internal-reset-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  return { root, filePath: path.join(root, 'monitor.json'), announcementPath: path.join(root, 'announcements.json') };
}
test('monitor persists settings, rejects stale windows, and never depends on native automations', async t => {
  const f = await fixture(t);
  const control = createResetMonitorController({filePath:f.filePath,now:()=>NOW});
  const initial = await control.snapshot();
  assert.equal(initial.enabled, true); assert.equal(initial.intervalMinutes, 15); assert.equal(initial.running, false);
  const saved = await control.request({...initial,action:'save',intervalMinutes:6});
  assert.equal(saved.intervalMinutes, 6);
  assert.deepEqual(await createResetMonitorController({filePath:f.filePath,now:()=>NOW}).snapshot(), saved);
  assert.deepEqual(await control.request({...saved,action:'save'}), saved);
  await assert.rejects(control.request({...initial,action:'save',intervalHours:4}), /已变化/);
  const paused = await control.request({...saved,action:'save',enabled:false});
  assert.equal(paused.enabled,false); assert.equal(paused.nextRunAt,null);
  for (const value of [0, -1, 1.5, 169, NaN, Infinity, '3', null]) assert.throws(()=>resetIntervalHours(value));
  for (const value of [0, -1, 1.5, 10081, NaN, Infinity, '1', null]) assert.throws(()=>resetIntervalMinutes(value));
  await writeFile(f.filePath, 'broken');
  await assert.rejects(control.snapshot());
  assert.equal(await readFile(f.filePath,'utf8'),'broken');
});
test('worker lock allows a single live owner and can reclaim dead owners', async t => {
  const f=await fixture(t), lock=path.join(f.root,'lock');
  const release=await acquireMonitorLock(lock);
  assert.equal(await acquireMonitorLock(lock),null);
  await release();
  await writeFile(lock,JSON.stringify({pid:2147483647,token:'dead'}));
  const recovered=await acquireMonitorLock(lock); assert.ok(recovered); await recovered();
});
test('rules recognize explicit reset types/times, not speculation, quotes or API feature announcements', () => {
  const classify=text=>classifyResetPost({...POST,text},[],NOW);
  const planned=classify('We will reset Codex usage for Pro users in two hours.');
  assert.equal(planned?.status,'scheduled'); assert.equal(planned.targetAt,'2026-09-27T14:00:00.000Z');
  assert.equal(planned.scope,'Pro'); assert.equal(planned.verification,'rss');
  assert.notEqual(planned.deliveryStatus,'delivered');
  const banked=classify('We are adding a banked reset for Plus and Pro users.');
  assert.equal(banked?.status,'tentative'); assert.equal(banked.resetType,'banked'); assert.equal(banked.targetAt,null);
  assert.equal(classify('We have granted a banked reset to Plus users.')?.status,'completed');
  assert.equal(classify('Resets all propagated. That will be all. Have a fantastic weekend.')?.status,'completed');
  assert.equal(classify('Reset all propagated. Sweet dreams.')?.status,'completed');
  for(const text of ['I hope Codex will reset in two hours.', 'Will Codex reset in two hours?', 'RT @other: We will reset Codex in two hours.', 'We will not reset Codex.', 'Someone said "Codex reset is coming".', 'We will discuss Codex reset support in two hours.', 'We added a reset button for Codex.', 'We will add a reset feature to Codex.']) assert.equal(classify(text),null,text);
  const completed=classifyResetPost({...POST,text:'Codex reset fully propagated.',references:['2100000000000000000']},[{id:'2100000000000000000'}],NOW);
  assert.equal(completed.status,'completed'); assert.deepEqual(completed.supersedes,['2100000000000000000']);
  assert.ok(completed.evidence.split(/\s+/).length<=25);
});
test('time parser distinguishes deadline/window and does not guess ambiguous dates or zones', () => {
  const time=text=>extractResetTime(text,POST.publishedAt);
  assert.equal(time('within 3 hours').precision,'deadline');
  assert.equal(time('in 2-5 hours').precision,'window');
  assert.equal(time('in 2-5 hours').windowStartAt,'2026-09-27T14:00:00.000Z');
  assert.equal(time('2026-09-28 09:00 PST').targetAt,'2026-09-28T17:00:00.000Z');
  assert.equal(time('2026-09-28 09:00 PDT').targetAt,'2026-09-28T16:00:00.000Z');
  assert.equal(time('by 2026-09-28T09:00:00+08:00').precision,'deadline');
  for(const text of ['tomorrow morning','midnight','soon','2026-09-28 09:00','about in 2 hours','after 2 hours','in 2-40 hours','2026-02-30 09:00 UTC','2026-02-30T09:00:00Z']) assert.equal(time(text),null,text);
});
test('standalone worker collects and deduplicates without a renderer, skips early/paused checks, preserves state on failure', async t => {
  const f=await fixture(t); let calls=0;
  const fetchImpl=async()=>{calls++;return new Response(`<rss><channel><link>https://x.com/thsottiaux</link><item><link>${POST.sourceUrl}</link><pubDate>${new Date(NOW).toUTCString()}</pubDate><description>We will reset Codex usage for Pro users in two hours.</description></item></channel></rss>`);};
  const first=await tickResetMonitor({...f,now:NOW,fetchImpl});
  assert.equal(first.lastStatus,'ok'); assert.equal(first.lastEventCount,1);
  let state=await readResetAnnouncements(f.announcementPath);
  assert.equal(state.events.length,1); assert.equal(state.reviewedPosts.length,1);
  assert.equal((await tickResetMonitor({...f,now:NOW+1000,fetchImpl})).checked,false); assert.equal(calls,1);
  const control=createResetMonitorController({filePath:f.filePath,now:()=>NOW});
  let snapshot=await control.snapshot(); assert.equal(snapshot.running,true);
  snapshot=await control.request({...snapshot,action:'save',enabled:false});
  assert.equal((await tickResetMonitor({...f,now:NOW+8*3600000,fetchImpl,force:true})).checked,false); assert.equal(calls,1);
  await control.request({...snapshot,action:'save',enabled:true,intervalMinutes:360});
  const second=await tickResetMonitor({...f,now:NOW+12*3600000,fetchImpl});
  assert.equal(second.lastEventCount,0); assert.equal(calls,2,'one overdue check, not every missed interval');
  const failed=await tickResetMonitor({...f,now:NOW+18*3600000,fetchImpl:async()=>{throw Error('offline')}});
  assert.equal(failed.lastStatus,'error');
  state=await readResetAnnouncements(f.announcementPath);
  assert.equal(state.events.length,1); assert.equal(state.reviewedPosts.length,1);
  assert.equal((await readResetMonitorStatus(f.filePath)).nextRunAt,NOW+24*3600000);
});
test('minute polling, failure backoff, recovery and legacy hour configuration use the actual schedule', async t => {
  const f=await fixture(t), control=createResetMonitorController({filePath:f.filePath,now:()=>NOW});
  await control.request({...await control.snapshot(),action:'save',intervalMinutes:1});
  let calls=0;
  const fetchImpl=async()=>{calls++;return new Response(`<rss><channel><link>https://x.com/thsottiaux</link><item><link>${POST.sourceUrl}</link><pubDate>${new Date(NOW).toUTCString()}</pubDate><description>Resets all propagated. That will be all.</description></item></channel></rss>`)};
  const initial=await tickResetMonitor({...f,now:NOW,fetchImpl});
  assert.equal(initial.lastStatus,'ok'); assert.equal(initial.lastEventCount,1);
  assert.equal(initial.nextRunAt,NOW+60_000);
  assert.equal((await tickResetMonitor({...f,now:NOW+59_999,fetchImpl})).checked,false);
  assert.equal((await tickResetMonitor({...f,now:NOW+60_000,fetchImpl})).checked,true);
  assert.equal(calls,2);
  const failure=await tickResetMonitor({...f,now:NOW+120_000,fetchImpl:async()=>{throw Error('offline')}});
  assert.equal(failure.nextRunAt,NOW+240_000);
  assert.equal((await control.snapshot()).nextRunAt,failure.nextRunAt);
  assert.equal((await tickResetMonitor({...f,now:NOW+180_000,fetchImpl})).checked,false);
  assert.equal((await tickResetMonitor({...f,now:NOW+240_000,fetchImpl})).nextRunAt,NOW+300_000);
  await writeFile(f.filePath,JSON.stringify({schemaVersion:1,revision:'legacy',enabled:true,intervalHours:6,updatedAt:NOW}));
  assert.equal((await control.snapshot()).intervalMinutes,360);
  const fast=await control.request({...await control.snapshot(),action:'save',intervalMinutes:1});
  assert.equal(fast.intervalMinutes,1);
});
test('macOS monitor installs an independent login service, never launching Codex', async t => {
  const f=await fixture(t), home=path.join(f.root,'user & test');
  const plan=createResetMonitorServicePlan({home,installDir:process.cwd()});
  assert.match(plan.plist,/KeepAlive/); assert.match(plan.plist,/reset-monitor-worker/);
  assert.doesNotMatch(plan.plist,/injector|heartbeat|\/usr\/bin\/open/);
  assert.match(plan.plist,/user &amp; test/);
  const result=await installResetMonitorService({home,installDir:process.cwd(),skipLaunchctl:true});
  assert.equal(await readFile(result.plistPath,'utf8'),plan.plist);
});
